package com.sdlc.templaterule;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class ClientTemplate implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	private java.lang.String clientName;
	private java.lang.String loginTemplate;
	private java.lang.String dashboardTemplate;
	private java.lang.String serviceTemplate;

	public ClientTemplate() {
	}

	public java.lang.String getClientName() {
		return this.clientName;
	}

	public void setClientName(java.lang.String clientName) {
		this.clientName = clientName;
	}

	public java.lang.String getLoginTemplate() {
		return this.loginTemplate;
	}

	public void setLoginTemplate(java.lang.String loginTemplate) {
		this.loginTemplate = loginTemplate;
	}

	public java.lang.String getDashboardTemplate() {
		return this.dashboardTemplate;
	}

	public void setDashboardTemplate(java.lang.String dashboardTemplate) {
		this.dashboardTemplate = dashboardTemplate;
	}

	public java.lang.String getServiceTemplate() {
		return this.serviceTemplate;
	}

	public void setServiceTemplate(java.lang.String serviceTemplate) {
		this.serviceTemplate = serviceTemplate;
	}

	public ClientTemplate(java.lang.String clientName,
			java.lang.String loginTemplate, java.lang.String dashboardTemplate,
			java.lang.String serviceTemplate) {
		this.clientName = clientName;
		this.loginTemplate = loginTemplate;
		this.dashboardTemplate = dashboardTemplate;
		this.serviceTemplate = serviceTemplate;
	}

}