package com.myspace.creditscore;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class CreditScore implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	private java.lang.Integer score;
	private java.lang.String status;

	public CreditScore() {
	}

	public java.lang.Integer getScore() {
		return this.score;
	}

	public void setScore(java.lang.Integer score) {
		this.score = score;
	}

	public java.lang.String getStatus() {
		return this.status;
	}

	public void setStatus(java.lang.String status) {
		this.status = status;
	}

	public CreditScore(java.lang.Integer score, java.lang.String status) {
		this.score = score;
		this.status = status;
	}

}