package com.sdlc.servicerulerepo;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class ConfigurableClientTemplate implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	private java.lang.String clientID;
	private java.lang.String template;
	private java.util.List<java.lang.String> serviceList;
	private java.util.List<java.lang.String> componentList;

	public ConfigurableClientTemplate() {
	}

	public java.lang.String getClientID() {
		return this.clientID;
	}

	public void setClientID(java.lang.String clientID) {
		this.clientID = clientID;
	}

	public java.lang.String getTemplate() {
		return this.template;
	}

	public void setTemplate(java.lang.String template) {
		this.template = template;
	}

	public java.util.List<java.lang.String> getServiceList() {
		return this.serviceList;
	}

	public void setServiceList(java.util.List<java.lang.String> serviceList) {
		this.serviceList = serviceList;
	}

	public java.util.List<java.lang.String> getComponentList() {
		return this.componentList;
	}

	public void setComponentList(java.util.List<java.lang.String> componentList) {
		this.componentList = componentList;
	}

	public ConfigurableClientTemplate(java.lang.String clientID,
			java.lang.String template,
			java.util.List<java.lang.String> serviceList,
			java.util.List<java.lang.String> componentList) {
		this.clientID = clientID;
		this.template = template;
		this.serviceList = serviceList;
		this.componentList = componentList;
	}

}